/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.componio.opencms.projectstructure.plugin.dialogs;

import java.io.File;
import java.io.IOException;
import java.util.Enumeration;
import org.apache.tools.ant.module.api.support.ActionUtils;
import org.openide.filesystems.FileObject;
import org.openide.util.Exceptions;

/**
 *
 * @author Tom
 */
public class CreateNewResourceTypePanel extends javax.swing.JPanel {

    private FileObject buildScript;
    private FileObject projectDirectory;

    private String ide_project;
    private String ide_schemas;
    private String ide_formatters;
    private String ide_scripts;
    private String ide_web;

    /**
     * Creates new form CreateNewResourceTypePanel
     */
    public CreateNewResourceTypePanel(FileObject buildScript, FileObject projectDirectory) {
        initComponents();
        initVariables(buildScript, projectDirectory);
        initPaths();
    }

    private void initVariables(FileObject buildScript, FileObject projectDirectory) {
        this.buildScript = buildScript;
        this.projectDirectory = projectDirectory;
    }

    private void initPaths() {
        File project = new File(projectDirectory.getPath());
        ide_project = project.exists() ? project.getAbsolutePath().replace("\\", "/") : "";

        File web = new File(projectDirectory.getFileObject("Web").getPath());
        ide_web = web.exists() ? web.getAbsolutePath().replace("\\", "/") : "";

        File schemas = new File(projectDirectory.getFileObject("Web").getFileObject("schemas").getPath());
        ide_schemas = schemas.exists() ? schemas.getAbsolutePath().replace("\\", "/") : "";

        File formatters = new File(projectDirectory.getFileObject("Web").getFileObject("formatters").getPath());
        ide_formatters = formatters.exists() ? formatters.getAbsolutePath().replace("\\", "/") : "";

        File scripts = new File(projectDirectory.getFileObject("scripts").getPath());
        ide_scripts = scripts.exists() ? scripts.getAbsolutePath().replace("\\", "/") : "";
    }
    
    private void generateCmsShellScriptForNewResourceType() {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_resource_type_id = new javax.swing.JLabel();
        label_resource_type_name = new javax.swing.JLabel();
        label_resource_type_nice_name = new javax.swing.JLabel();
        label_resource_type_title = new javax.swing.JLabel();
        label_schema_type_name = new javax.swing.JLabel();
        textfield_resource_type_id = new javax.swing.JTextField();
        textfield_resource_type_name = new javax.swing.JTextField();
        textfield_resource_type_nice_name = new javax.swing.JTextField();
        textfield_resource_type_title = new javax.swing.JTextField();
        label_resource_type_description = new javax.swing.JLabel();
        textfield_resource_type_description = new javax.swing.JTextField();
        textfield_schema_type_name = new javax.swing.JTextField();
        button_save = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();

        org.openide.awt.Mnemonics.setLocalizedText(label_resource_type_id, org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.label_resource_type_id.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(label_resource_type_name, org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.label_resource_type_name.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(label_resource_type_nice_name, org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.label_resource_type_nice_name.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(label_resource_type_title, org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.label_resource_type_title.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(label_schema_type_name, org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.label_schema_type_name.text")); // NOI18N

        textfield_resource_type_id.setText(org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.textfield_resource_type_id.text")); // NOI18N

        textfield_resource_type_name.setText(org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.textfield_resource_type_name.text")); // NOI18N

        textfield_resource_type_nice_name.setText(org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.textfield_resource_type_nice_name.text")); // NOI18N

        textfield_resource_type_title.setText(org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.textfield_resource_type_title.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(label_resource_type_description, org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.label_resource_type_description.text")); // NOI18N

        textfield_resource_type_description.setText(org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.textfield_resource_type_description.text")); // NOI18N

        textfield_schema_type_name.setText(org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.textfield_schema_type_name.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(button_save, org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.button_save.text")); // NOI18N
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(button_cancel, org.openide.util.NbBundle.getMessage(CreateNewResourceTypePanel.class, "CreateNewResourceTypePanel.button_cancel.text")); // NOI18N
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_resource_type_id)
                            .addComponent(label_resource_type_name)
                            .addComponent(label_resource_type_nice_name)
                            .addComponent(label_resource_type_title)
                            .addComponent(label_resource_type_description)
                            .addComponent(label_schema_type_name))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfield_resource_type_id)
                            .addComponent(textfield_resource_type_name)
                            .addComponent(textfield_resource_type_nice_name)
                            .addComponent(textfield_resource_type_title)
                            .addComponent(textfield_resource_type_description)
                            .addComponent(textfield_schema_type_name, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_cancel)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_resource_type_id)
                    .addComponent(textfield_resource_type_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_resource_type_name)
                    .addComponent(textfield_resource_type_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_resource_type_nice_name)
                    .addComponent(textfield_resource_type_nice_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_resource_type_title)
                    .addComponent(textfield_resource_type_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_resource_type_description)
                    .addComponent(textfield_resource_type_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfield_schema_type_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_schema_type_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_save)
                    .addComponent(button_cancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        generateCmsShellScriptForNewResourceType();
        try {
            ActionUtils.runTarget(buildScript, new String[]{"build_create_new_resource_type"}, null);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        } catch (IllegalArgumentException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_button_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel label_resource_type_description;
    private javax.swing.JLabel label_resource_type_id;
    private javax.swing.JLabel label_resource_type_name;
    private javax.swing.JLabel label_resource_type_nice_name;
    private javax.swing.JLabel label_resource_type_title;
    private javax.swing.JLabel label_schema_type_name;
    private javax.swing.JTextField textfield_resource_type_description;
    private javax.swing.JTextField textfield_resource_type_id;
    private javax.swing.JTextField textfield_resource_type_name;
    private javax.swing.JTextField textfield_resource_type_nice_name;
    private javax.swing.JTextField textfield_resource_type_title;
    private javax.swing.JTextField textfield_schema_type_name;
    // End of variables declaration//GEN-END:variables
}
