/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.componio.maven.opencms.netbeans.plugin;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import org.netbeans.spi.project.ui.support.ProjectChooser;
import org.openide.WizardDescriptor;
import org.openide.WizardValidationException;
import org.openide.filesystems.FileUtil;

public class OpenCmsMavenTemplatePanelVisual extends JPanel implements DocumentListener {

    public static final String PROP_PROJECT_NAME = "projectName";

    private OpenCmsMavenTemplateWizardPanel panel;

    public OpenCmsMavenTemplatePanelVisual(OpenCmsMavenTemplateWizardPanel panel) {
        initComponents();
        this.panel = panel;
        // Register listener on the textFields to make the automatic updates
        projectNameTextField.getDocument().addDocumentListener(this);
        projectLocationTextField.getDocument().addDocumentListener(this);
    }

    public String getProjectName() {
        return this.projectNameTextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectNameLabel = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        projectLocationLabel = new javax.swing.JLabel();
        projectLocationTextField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        createdFolderLabel = new javax.swing.JLabel();
        createdFolderTextField = new javax.swing.JTextField();
        opencmsWebInfPath = new javax.swing.JLabel();
        openCmsWebInfTextField = new javax.swing.JTextField();
        browseButtonOpenCmsWebInf = new javax.swing.JButton();
        OpenCmsVersionLabel = new javax.swing.JLabel();
        opencmsVersionComboBox = new javax.swing.JComboBox();
        mavenHomeLabel = new javax.swing.JLabel();
        mavenHomeTextField = new javax.swing.JTextField();
        browseButtonMavenHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(255, 255, 255));

        projectNameLabel.setLabelFor(projectNameTextField);
        org.openide.awt.Mnemonics.setLocalizedText(projectNameLabel, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.projectNameLabel.text")); // NOI18N

        projectLocationLabel.setLabelFor(projectLocationTextField);
        org.openide.awt.Mnemonics.setLocalizedText(projectLocationLabel, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.projectLocationLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(browseButton, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.browseButton.text")); // NOI18N
        browseButton.setActionCommand(org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.browseButton.actionCommand")); // NOI18N
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        createdFolderLabel.setLabelFor(createdFolderTextField);
        org.openide.awt.Mnemonics.setLocalizedText(createdFolderLabel, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.createdFolderLabel.text")); // NOI18N

        createdFolderTextField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(opencmsWebInfPath, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.opencmsWebInfPath.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(browseButtonOpenCmsWebInf, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.browseButtonOpenCmsWebInf.text")); // NOI18N
        browseButtonOpenCmsWebInf.setActionCommand(org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.browseButtonOpenCmsWebInf.actionCommand")); // NOI18N
        browseButtonOpenCmsWebInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonOpenCmsWebInfActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(OpenCmsVersionLabel, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.OpenCmsVersionLabel.text")); // NOI18N

        opencmsVersionComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8.5.0", "8.5.1", "8.5.2", "9.0.0", "9.0.1", "9.5.0", "9.5.1", "9.5.2", "9.5.3", "10.0.0", "10.0.1" }));
        opencmsVersionComboBox.setToolTipText(org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.opencmsVersionComboBox.toolTipText")); // NOI18N
        opencmsVersionComboBox.setAutoscrolls(true);
        opencmsVersionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opencmsVersionComboBoxActionPerformed(evt);
            }
        });

        mavenHomeLabel.setLabelFor(createdFolderTextField);
        org.openide.awt.Mnemonics.setLocalizedText(mavenHomeLabel, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.mavenHomeLabel.text")); // NOI18N

        mavenHomeTextField.setEditable(true);

        org.openide.awt.Mnemonics.setLocalizedText(browseButtonMavenHome, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.browseButtonMavenHome.text")); // NOI18N
        browseButtonMavenHome.setActionCommand(org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.browseButtonMavenHome.actionCommand")); // NOI18N
        browseButtonMavenHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonMavenHomeActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/componio/maven/opencms/netbeans/plugin/componio.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(OpenCmsMavenTemplatePanelVisual.class, "OpenCmsMavenTemplatePanelVisual.jLabel1.toolTipText")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectNameLabel)
                                    .addComponent(projectLocationLabel)
                                    .addComponent(createdFolderLabel))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mavenHomeLabel)
                                    .addComponent(opencmsWebInfPath, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(openCmsWebInfTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                            .addComponent(mavenHomeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createdFolderTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(projectLocationTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(projectNameTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseButtonOpenCmsWebInf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseButtonMavenHome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OpenCmsVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opencmsVersionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectLocationLabel)
                    .addComponent(projectLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createdFolderLabel)
                    .addComponent(createdFolderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mavenHomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mavenHomeLabel)
                    .addComponent(browseButtonMavenHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openCmsWebInfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButtonOpenCmsWebInf)
                    .addComponent(opencmsWebInfPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OpenCmsVersionLabel)
                    .addComponent(opencmsVersionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        String command = evt.getActionCommand();
        if ("BROWSE".equals(command)) {
            JFileChooser chooser = getFileChooser("Select Project Location", JFileChooser.DIRECTORIES_ONLY);
            //FileUtil.preventFileChooserSymlinkTraversal(chooser, null);
            String path = this.projectLocationTextField.getText();
            setPathForFileChooser(chooser, path);
            if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
                File projectDir = chooser.getSelectedFile();
                projectLocationTextField.setText(FileUtil.normalizeFile(projectDir).getAbsolutePath());
            }
            panel.fireChangeEvent();
        }

    }//GEN-LAST:event_browseButtonActionPerformed

    private void browseButtonOpenCmsWebInfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonOpenCmsWebInfActionPerformed
        String command = evt.getActionCommand();
        if ("BROWSE".equals(command)) {
            //FileUtil.preventFileChooserSymlinkTraversal(chooser, null);
            JFileChooser chooser = getFileChooser("Select OpenCms WEB-INF Location", JFileChooser.DIRECTORIES_ONLY);
            String path = this.openCmsWebInfTextField.getText();
            setPathForFileChooser(chooser, path);
            if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
                File webInfDir = chooser.getSelectedFile();
                String webInfPath = FileUtil.normalizeFile(webInfDir).getAbsolutePath();
                webInfPath = webInfPath.replace("\\", "/");
                openCmsWebInfTextField.setText(webInfPath);
            }
            panel.fireChangeEvent();
        }
    }//GEN-LAST:event_browseButtonOpenCmsWebInfActionPerformed

    private void opencmsVersionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opencmsVersionComboBoxActionPerformed
        
    }//GEN-LAST:event_opencmsVersionComboBoxActionPerformed

    

    private void browseButtonMavenHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonMavenHomeActionPerformed
        String command = evt.getActionCommand();
        if ("BROWSE".equals(command)) {
            //FileUtil.preventFileChooserSymlinkTraversal(chooser, null);
            JFileChooser chooser = getFileChooser("Select Maven Home Directory", JFileChooser.DIRECTORIES_ONLY);
            String path = this.mavenHomeTextField.getText();
            setPathForFileChooser(chooser, path);
            if (JFileChooser.APPROVE_OPTION == chooser.showOpenDialog(this)) {
                File webInfDir = chooser.getSelectedFile();
                String webInfPath = FileUtil.normalizeFile(webInfDir).getAbsolutePath();
                webInfPath = webInfPath.replace("\\", "/");
                mavenHomeTextField.setText(webInfPath);
            }
            panel.fireChangeEvent();
        }
    }//GEN-LAST:event_browseButtonMavenHomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OpenCmsVersionLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton browseButtonMavenHome;
    private javax.swing.JButton browseButtonOpenCmsWebInf;
    private javax.swing.JLabel createdFolderLabel;
    private javax.swing.JTextField createdFolderTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mavenHomeLabel;
    private javax.swing.JTextField mavenHomeTextField;
    private javax.swing.JTextField openCmsWebInfTextField;
    private javax.swing.JComboBox opencmsVersionComboBox;
    private javax.swing.JLabel opencmsWebInfPath;
    private javax.swing.JLabel projectLocationLabel;
    private javax.swing.JTextField projectLocationTextField;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addNotify() {
        super.addNotify();
        //same problem as in 31086, initial focus on Cancel button
        projectNameTextField.requestFocus();
    }

    boolean valid(WizardDescriptor wizardDescriptor) {

        if (projectNameTextField.getText().length() == 0) {
            // TODO if using org.openide.dialogs >= 7.8, can use WizardDescriptor.PROP_ERROR_MESSAGE:
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    "Project Name is not a valid folder name.");
            return false; // Display name not specified
        }
        File f = FileUtil.normalizeFile(new File(projectLocationTextField.getText()).getAbsoluteFile());
        if (!f.isDirectory()) {
            String message = "Project Folder is not a valid path.";
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message);
            return false;
        }
        final File destFolder = FileUtil.normalizeFile(new File(createdFolderTextField.getText()).getAbsoluteFile());

        File projLoc = destFolder;
        while (projLoc != null && !projLoc.exists()) {
            projLoc = projLoc.getParentFile();
        }
        if (projLoc == null || !projLoc.canWrite()) {
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    "Project Folder cannot be created.");
            return false;
        }

        if (FileUtil.toFileObject(projLoc) == null) {
            String message = "Project Folder is not a valid path.";
            wizardDescriptor.putProperty("WizardPanel_errorMessage", message);
            return false;
        }

        File[] kids = destFolder.listFiles();
        if (destFolder.exists() && kids != null && kids.length > 0) {
            // Folder exists and is not empty
            wizardDescriptor.putProperty("WizardPanel_errorMessage",
                    "Project Folder already exists and is not empty.");
            return false;
        }
        wizardDescriptor.putProperty("WizardPanel_errorMessage", "");
        return true;
    }

    void store(WizardDescriptor d) {
        String name = projectNameTextField.getText().trim();
        String folder = createdFolderTextField.getText().trim();
        String opencmsVersion = opencmsVersionComboBox.getSelectedItem().toString().trim();
        String opencmsWebInf = openCmsWebInfTextField.getText().trim();
        String mavenHome = mavenHomeTextField.getText().trim();
        d.putProperty("projdir", new File(folder));
        d.putProperty("name", name);
        d.putProperty("opencmsVersion", opencmsVersion);
        d.putProperty("opencmsWebInf", opencmsWebInf);
        d.putProperty("mavenHome", mavenHome);

    }

    void read(WizardDescriptor settings) {
        File projectLocation = (File) settings.getProperty("projdir");
        if (projectLocation == null || projectLocation.getParentFile() == null || !projectLocation.getParentFile().isDirectory()) {
            projectLocation = ProjectChooser.getProjectsFolder();
        } else {
            projectLocation = projectLocation.getParentFile();
        }
        this.projectLocationTextField.setText(projectLocation.getAbsolutePath());

        String projectName = (String) settings.getProperty("name");
        if (projectName == null) {
            projectName = "OpenCmsMavenTemplate";
        }
        this.projectNameTextField.setText(projectName);
        this.projectNameTextField.selectAll();
    }

    void validate(WizardDescriptor d) throws WizardValidationException {
        // nothing to validate
    }

    // Implementation of DocumentListener --------------------------------------
    public void changedUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    public void insertUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    public void removeUpdate(DocumentEvent e) {
        updateTexts(e);
        if (this.projectNameTextField.getDocument() == e.getDocument()) {
            firePropertyChange(PROP_PROJECT_NAME, null, this.projectNameTextField.getText());
        }
    }

    /**
     * Handles changes in the Project name and project directory,
     */
    private void updateTexts(DocumentEvent e) {

        Document doc = e.getDocument();

        if (doc == projectNameTextField.getDocument() || doc == projectLocationTextField.getDocument()) {
            // Change in the project name

            String projectName = projectNameTextField.getText();
            String projectFolder = projectLocationTextField.getText();

            //if (projectFolder.trim().length() == 0 || projectFolder.equals(oldName)) {
            createdFolderTextField.setText(projectFolder + File.separatorChar + projectName);
            //}

        }
        panel.fireChangeEvent(); // Notify that the panel changed
    }
    
    JFileChooser getFileChooser(String dialogTitle, int selectionMode) {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle(dialogTitle);
        chooser.setFileSelectionMode(selectionMode);
        return chooser;
    }

    private void setPathForFileChooser(JFileChooser chooser, String path) {
        if (path.length() > 0) {
            if (new File(path).exists()) {
                chooser.setSelectedFile(new File(path));
            }
        }
    }

}
